# .github/workflows/daily_ai_news.yml
# Place this file at: .github/workflows/daily_ai_news.yml in your repo

name: Daily AI News Email

on:
  schedule:
    - cron: '0 13 * * *'   # 8:00 AM EST (UTC-5) — adjust for your timezone
                             # 0 14 * * * = 9am EST, 0 8 * * * = 8am UTC, etc.
  workflow_dispatch:         # Allows manual runs from the GitHub Actions UI

jobs:
  send-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install anthropic

      - name: Run AI news agent
        env:
          ANTHROPIC_API_KEY:  ${{ secrets.ANTHROPIC_API_KEY }}
          GMAIL_ADDRESS:      ${{ secrets.GMAIL_ADDRESS }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          TO_EMAIL:           ${{ secrets.TO_EMAIL }}
        run: python ai_news_agent.py
